apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 80
  selector:
    io.kompose.service: admin
status:
  loadBalancer: {}
