apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: release
        - name: RAQUETTE_HOST
          value: raquette-redis:6380
        - name: TENNIS_HOST
          value: tennis-redis:6379
        image: poudreauxyeux/rapiquette
        name: api
        ports:
        - containerPort: 3333
        resources: {}
      restartPolicy: Always
status: {}
