apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: atp
  name: atp
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 80
  selector:
    io.kompose.service: atp
status:
  loadBalancer: {}
