apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: tennis-redis
  name: tennis-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tennis-redis
    spec:
      containers:
      - args:
        - redis-server
        - --appendonly
        - "yes"
        image: redis:4.0.8-alpine
        name: tennis-redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: tennis-data
      restartPolicy: Always
      volumes:
      - name: tennis-data
        persistentVolumeClaim:
          claimName: tennis-data
status: {}
